name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write  # necessário para criar a release

    env:
      PROJECT: src/GameManagement/GameManagement.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get version from input
      id: tag_name
      shell: bash
      env:
        INPUT_VERSION: ${{ github.event.inputs.version }}
      run: |
        echo "current_version=${INPUT_VERSION}" >> $GITHUB_OUTPUT

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Installing pip dependencies
      run: pip install -r requirements.txt

    - name: Setup .NET 6.0.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Clear local NuGet cache
      run: dotnet clean $env:PROJECT && dotnet nuget locals all --clear

    - name: Restore dependencies
      run: dotnet restore $env:PROJECT

    - name: Build GameManagement
      run: dotnet build $env:PROJECT --no-restore -p:Version="${{ steps.tag_name.outputs.current_version }}"

    - name: Change Version (update manifests)
      run: python scripts/build.py update ${{ steps.tag_name.outputs.current_version }}

    - name: Install Playnite Toolbox
      run: dotnet tool install --global Playnite.Toolbox

    - name: Pack Extension
      shell: bash
      run: |
        mkdir -p out
        toolbox pack --input "src/GameManagement/bin/Debug/net462/" --output "out/" --name "GameManagement_${{ steps.tag_name.outputs.current_version }}.pext"

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.tag_name.outputs.current_version }}
        name: Release ${{ steps.tag_name.outputs.current_version }}
        body: "[Changelog](https://github.com/erri120/Playnite.Extensions/blob/master/CHANGELOG.md)"
        draft: false
        prerelease: false
        files: |
          out/GameManagement_${{ steps.tag_name.outputs.current_version }}.pext

    - name: Commit and Push Installer Manifests
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update GameManagement Installer Manifest
        file_pattern: manifests/GameManagement.yaml src/GameManagement/extension.yaml
